### ISSUE TITLE
Plain .aspx support (old WebForms) ?

### ISSUE THREAD

**Issue by DNS** [wshearn/openshift-community-cartridge-mono#1]
I've tried this cartrigde and it works perfectly, but it use MVC4.

Do you know how to enable old ASP .NET WebForms (plain .aspx files) on OpenShift ?

**Comment by hindermath** [comment]
Try my test.aspx page in my Mono cartridge in the rhcloud at http://mono-hindermath.rhcloud.com/test.aspx. The website based on the default Mono cartridge from wshearn and I includes the following plain aspx file withe the following easy code from this URL
http://msdn.microsoft.com/en-us/library/015103yb(v=vs.100).aspx
It runs fine in the Mono Cartridge!

**Comment by DNS** [comment]
Thanks, I already solve the problem by asking the author "wshearn" on openshift dev mailing list

**Comment by hindermath** [comment]
Ok, thanx for your answer.

**Comment by wshearn** [comment]
o_O How did I miss this one. Ohh well the thread in question https://lists.openshift.redhat.com/openshift-archives/dev/2013-July/msg00163.html (for people later)
