### ISSUE TITLE
Get the latest Mono binary ?

### ISSUE THREAD

**Issue by DNS** [wshearn/openshift-community-cartridge-mono#11]
is there a way to always get the latest binary from www.mono-project.com, perhaps using modified yum, and automatically install to local user directory ?

Building mono sources on openshift account (via ssh) always fail because the File number limit quota. Would be nice if openshift officialy support Mono.

**Comment by wshearn** [comment]
The latest binary packages they have for linux is version 3.2.3 and that is only for OpenSUSE which may have(I have not tested) been built with a newer (major) version of glibc that is not binary compatible with RHEL. 

So long answer short, no, not really. As for building the mono sources on an openshift account yeah that may take a long time. Best bet would be to build it in a RHEL or CentOS VM and update the scripts in the bin directory to use ${OPENSHIFT_MONO_DIR}/mono/bin/. Then copy those up.
