### ISSUE TITLE
still alive?

### ISSUE THREAD

**Issue by angelcolmenares** [wshearn/openshift-community-cartridge-mono#12]
hi,
are you still working on this project?
any news?

**Comment by wshearn** [comment]
yes, i plan to upgrade to the latest mono version soon, no time line yet.

**Comment by albertdb** [comment]
Hi,

I'm considering using Openshift with this cartridge to deploy my Mono applications. What makes me worry is that this repository hasn't receive an update in 2 years and scaling doesn't work out of the box.

Will we see an update in a short-term? It would be really great.

Thanks!

**Comment by samasama** [comment]
This is an updated version of the cartridge fixing a couple of issues
samasama/openshift_mono_cart

|   |
|   |  |   |   |   |   |   |
| samasama/openshift_mono_cartContribute to openshift_mono_cart development by creating an account on GitHub. |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |

```
  From: albertdb <notifications@github.com>
```

 To: wshearn/openshift-community-cartridge-mono openshift-community-cartridge-mono@noreply.github.com 
 Sent: Thursday, June 11, 2015 11:59 PM
 Subject: Re: [openshift-community-cartridge-mono] still alive? (#12)

Hi,I'm considering using Openshift with this cartridge to deploy my Mono applications. What makes me worry is that this repository hasn't receive an update in 2 years and scaling doesn't work out of the box.Will we see an update in a short-term? It would be really great.Thanks!—
