### ISSUE TITLE
Update to the new 3.2.1 Mono cartridge

### ISSUE THREAD

**Issue by hindermath** [wshearn/openshift-community-cartridge-mono#5]
How I can update my running Mono cartridges in OpenShift.com to this new Mono version 3.2.1? Is that done automatically or should I install the new cartridge? Can you give me advice about this procedure?

**Comment by wshearn** [comment]
You will have to create a new application using https://raw.github.com/wshearn/openshift-community-cartridge-mono/3.2.1/metadata/manifest.yml (or if you want the ASPX version[still working on getting working] https://raw.github.com/wshearn/openshift-community-cartridge-mono/3.2.1-aspx/metadata/manifest.yml).

Using the RHC utility you can back up your application with rhc-snapshot and then restore it on the new gears using mono 3.2.1.

**Comment by olakara** [comment]
How do I update to the latest version of Mono .. the version 3.4? Do you have a new version of manifest file?

**Comment by wshearn** [comment]
I will be updating to 3.10(or the latest at the time) soon, no time line yet.
