### ISSUE TITLE
Difference between 3.2.1 and 3.2.1-aspx

### ISSUE THREAD

**Issue by hindermath** [wshearn/openshift-community-cartridge-mono#7]
Can you explain the difference between mono 3.2.1 an 3.2.1-aspx trees?

**Comment by wshearn** [comment]
This https://lists.openshift.redhat.com/openshift-archives/dev/2013-July/msg00164.html those changes are already done. So it is for aspx pages and not MVC. It is on my to do list to have them to work with the same configuration setup.
